export const FEATURE_FLAGS = {
  KNOWLEDGE_AGENT_ENABLED: true,
  DOCUMENT_UPLOAD_ENABLED: true,
  BASIC_AUTH_ENABLED: true,
  MULTI_TENANT_ENABLED: true,
  ANALYTICS_DASHBOARD_ENABLED: true,
  PROJECT_AGENT_ENABLED: true,
  SLACK_WEBHOOK_ENABLED: true,
  JIRA_INTEGRATION_ENABLED: true,
  EMAIL_WEBHOOK_ENABLED: true,
  WORKLOAD_BALANCING_ENABLED: true,
  AUDIT_LOG_ENABLED: true,
  CUSTOM_LLM_PROVIDER_ENABLED: true,
  RAG_CACHE_ENABLED: true,
} as const;

export type FeatureFlag = keyof typeof FEATURE_FLAGS;
